CREATE TABLE IF NOT EXISTS guest_identity (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  client_token_hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uk_guest_identity_client_token UNIQUE (client_token_hash)
);
