ALTER TABLE search_record
  ADD COLUMN IF NOT EXISTS low_confidence BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE search_record
  ADD COLUMN IF NOT EXISTS message VARCHAR(500);

ALTER TABLE search_record
  ADD COLUMN IF NOT EXISTS guest_id VARCHAR(100) NOT NULL DEFAULT 'guest';

ALTER TABLE feedback
  ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE admin_user
  ADD COLUMN IF NOT EXISTS created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
